### PR TITLE
Update to svd2rust v0.28.0

### PR DESCRIPTION
**Pull request by n8tlarsen**
I'm sure this breaks all the other pacs due to the changes in `generic.rs`, but this is the particular device I'm currently using 🤷‍♂️. It's a start anyway #1.

### CODE REVIEW

**Comment by n8tlarsen** [comment]
I'm having trouble getting the pac to compile when placed into a project due to the way the features are set up to select the target part. when compiling in a separate directory I have no issue, but inside this repo with the adjusted crate hierarchy, the generics folder doesn't compile with the correct imports and throws a number of errors.

**Comment by n8tlarsen** [comment]
Ah, nevermind, turned out it was an issue with missing portable atomic's features. The crate now compiles into another project. Sorry for all the force pushes, should have switched to local patching in Cargo.toml earlier.

**Comment by vpetrigo** [comment]
Thank you for your PR! I will take a look into that changes.

**Comment by vpetrigo** [comment]
@n8tlarsen, I updated the [gen-tools](https://github.com/efm32-rs/gen-tools) repository to use the latest (`0.28.0`) and update all EFM32 crates including this one.

I will close this PR and #1 as my changes should contain everything related to the `atomics` feature support. Feel free to open a new issue if anything missed.

Thank you once again for you contribution!

**Pull request closed without merging**
